---
- name: Add the user admin
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512') }}"
    shell: /bin/bash
    groups: "{{ item.groups }}"
    append: yes
  loop: "{{ users }}"
    
