# started/stopped - Testing: stopped
firewalld_state: stopped

ssh_port:
http_traefik_nodeport: 30080
https_traefik_nodeport: 30443

email:
git_username:
cert_repo:
cert_file: ssl-backup-2025-12-05.tar.gz.gpg

cockpit_domain: panel.aikode.cloud
k8s_dashboard_domain: k8s.aikode.cloud
wikijs_domain: wiki.aikode.cloud
jenkins_domain: jenkins.aikode.cloud

users:
  - name: admin1
    password: ""
    groups: wheel
    ssh_key: ""
  - name: admin2
    password: ""
    groups: wheel
    ssh_key: ""

packages:
  - epel-release
  - firewalld
  - fail2ban
  - git
  - nginx
  - python3
  - python3-pip
  - certbot
  - python3-certbot-nginx
  - gnupg
  - helm

services:
  - cockpit.socket
  - nginx