# started/stopped - Testing: stopped
firewalld_state: stopped

ssh_port:

email:
git_username:
ssl_backup_repo:

cockpit_domain:
k3s_domain:
k8s_dashboard_domain:
wikijs_domain:
jenkins_domain:

users:
  - name: admin
    password: ""
    groups: wheel
    ssh_key: ""

packages:
  - epel-release
  - firewalld
  - fail2ban
  - nginx
  - python3
  - python3-pip
  - certbot
  - python3-certbot-nginx
  - gnupg

services:
  - cockpit.socket
  - nginx