---
- name: Create sshd config file
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d/00-security.conf
    state: touch

- name: Copy sshd config template to config file
  ansible.builtin.template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config.d/00-security.conf